# Generated by Django 4.2.2 on 2023-06-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='recipes', through='app_recipes.RecipeIngredient', to='app_recipes.ingredient'),
        ),
    ]
